### ISSUE TITLE
Error extracting tables.

### ISSUE THREAD

**Issue by embrance** [ankane/dexter#11]
I have multiple databases on one postgresql instance, default postgresql configuration, Centos 7

used command: 

> tail -F -n +1 /data/postgresql-9.6/data/pg_log/postgresql-Wed.log | sudo -u postgres dexter DB_NAME --create

Output: 

Error extracting tables. Please report to https://github.com/ankane/dexter/issues/new
SELECT c.oid, a.attnum, a.attname, c.relname, n.nspname, a.attnotnull OR (t.typtype = 'd' AND t.typnotnull), pg_catalog.pg_get_expr(d.adbin, d.adrelid) LIKE '%nextval(%' FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON (c.relnamespace = n.oid) JOIN pg_catalog.pg_attribute a ON (c.oid = a.attrelid) JOIN pg_catalog.pg_type t ON (a.atttypid = t.oid) LEFT JOIN pg_catalog.pg_attrdef d ON (d.adrelid = a.attrelid AND d.adnum = a.attnum) JOIN (SELECT 155743 AS oid , 1 AS attnum UNION ALL SELECT 155743, 2 UNION ALL SELECT 155743, 3 UNION ALL SELECT 155743, 4 UNION ALL SELECT 155743, 5 UNION ALL SELECT 155743, 6 UNION ALL SELECT 155743, 7 UNION ALL SELECT 155743, 8 UNION ALL SELECT 155743, 9 UNION ALL SELECT 155743, 10 UNION ALL SELECT 155743, 11 UNION ALL SELECT 155743, 12 UNION ALL SELECT 155743, 13 UNION ALL SELECT 155743, 14 UNION ALL SELECT 155743, 15 UNION ALL SELECT 155743, 16 UNION ALL SELECT 155743, 17 UNION ALL SELECT 155743, 18 UNION ALL SELECT 155743, 19 UNION ALL SELECT 155743, 20 UNION ALL SELECT 155743, 21 UNION ALL SELECT 155743, 22 UNION ALL SELECT 155743, 26 UNION ALL SELECT 155743, 30 UNION ALL SELECT 155743, 37 UNION ALL SELECT 155743, 38 UNION ALL SELECT 155743, 39 UNION ALL SELECT 155743, 40 UNION ALL SELECT 155743, 79 UNION ALL SELECT 155743, 80 UNION ALL SELECT 155743, 81 UNION ALL SELECT 155743, 82 UNION ALL SELECT 155743, 83 UNION ALL SELECT 155743, 84 UNION ALL SELECT 155743, 85 UNION ALL SELECT 155743, 86 UNION ALL SELECT 155743, 87 UNION ALL SELECT 155743, 93 UNION ALL SELECT 155743, 94 UNION ALL SELECT 155743, 95 UNION ALL SELECT 155743, 96 UNION ALL SELECT 155743, 97 UNION ALL SELECT 155743, 98 UNION ALL SELECT 155743, 99 UNION ALL SELECT 155743, 100 UNION ALL SELECT 155743, 101 UNION ALL SELECT 155743, 102 UNION ALL SELECT 155743, 103 UNION ALL SELECT 155743, 104 UNION ALL SELECT 155743, 105 UNION ALL SELECT 155743, 106 UNION ALL SELECT 155743, 107 UNION ALL SELECT 155743, 108 UNION ALL SELECT 155743, 114 UNION ALL SELECT 155743, 115 UNION ALL SELECT 155743, 116 UNION ALL SELECT 155743, 119 UNION ALL SELECT 155743, 122 UNION ALL SELECT 155743, 125 UNION ALL SELECT 155743, 128 UNION ALL SELECT 155743, 129 UNION ALL SELECT 155743, 130 UNION ALL SELECT 155743, 133 UNION ALL SELECT 155743, 134 UNION ALL SELECT 155743, 135 UNION ALL SELECT 155743, 136 UNION ALL SELECT 155743, 137 UNION ALL SELECT 155743, 138 UNION ALL SELECT 155743, 139 UNION ALL SELECT 155743, 140 UNION ALL SELECT 155743, 141 UNION ALL SELECT 155743, 142 UNION ALL SELECT 155743, 143 UNION ALL SELECT 155743, 144 UNION ALL SELECT 155743, 145 UNION ALL SELECT 155743, 146 UNION ALL SELECT 155743, 147 UNION ALL SELECT 155743, 148 UNION ALL SELECT 155743, 149 UNION ALL SELECT 155743, 150 UNION ALL SELECT 155743, 194 UNION ALL SELECT 155743, 195 UNION ALL SELECT 155743, 199 UNION ALL SELECT 155743, 200 UNION ALL SELECT 155743, 201 UNION ALL SELECT 155743, 202 UNION ALL SELECT 155743, 203 UNION ALL SELECT 155743, 206 UNION ALL SELECT 155743, 207 UNION ALL SELECT 155743, 208 UNION ALL SELECT 155743, 209 UNION ALL SELECT 155743, 210 UNION ALL SELECT 155743, 211 UNION ALL SELECT 155743, 212 UNION ALL SELECT 155743, 213 UNION ALL SELECT 155743, 214 UNION ALL SELECT 155743, 215 UNION ALL SELECT 155743, 216 UNION ALL SELECT 155743, 217 UNION ALL SELECT 155743, 218 UNION ALL SELECT 155743, 219 UNION ALL SELECT 155743, 220 UNION ALL SELECT 155743, 221 UNION ALL SELECT 155743, 272 UNION ALL SELECT 155743, 273 UNION ALL SELECT 155743, 274 UNION ALL SELECT 155743, 275 UNION ALL SELECT 155743, 276 UNION ALL SELECT 155743, 282 UNION ALL SELECT 155743, 283 UNION ALL SELECT 155743, 284 UNION ALL SELECT 155743, 285 UNION ALL SELECT 155743, 286 UNION ALL SELECT 155743, 287 UNION ALL SELECT 155743, 288 UNION ALL SELECT 155743, 289 UNION ALL SELECT 155743, 290 UNION ALL SELECT 155743, 292 UNION ALL SELECT 155743, 319 UNION ALL SELECT 155743, 320 UNION ALL SELECT 155743, 326 UNION ALL SELECT 155743, 327 UNION ALL SELECT 155743, 328) vals ON (c.oid = vals.oid AND a.attnum = vals.attnum) 

tnum) 
/opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/indexer.rb:178:in `find_by_key': stack level too deep (SystemStackError)
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/indexer.rb:183:in `block in find_by_key'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/indexer.rb:179:in `each'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/indexer.rb:179:in `find_by_key'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/indexer.rb:183:in `block in find_by_key'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/indexer.rb:179:in `each'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/indexer.rb:179:in `find_by_key'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/indexer.rb:183:in `block in find_by_key'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/indexer.rb:179:in `each'
         ... 1270 levels...
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/processor.rb:49:in `process_queries'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/processor.rb:28:in `block (2 levels) in perform'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/processor.rb:26:in `loop'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-9ae34f22b530/lib/dexter/processor.rb:26:in `block in perform'

**Comment by ankane** [comment]
Hey @embrance, thanks for reporting 👍  Can you try updating to the latest version (`7423139c3`) and running it with `--log-level debug3`? Trying to see which statement it is getting stuck on.

**Comment by embrance** [comment]
Hi, thanks for reply :)

debug info: 
```
Finding columns: select "query_alias"."gid", "query_alias"."gid_code", "query_alias"."blocked", "query_alias"."pid", "query_alias"."pid_code", "query_alias"."pid_name", "query_alias"."pid_path" from (select "gid", "gid_code", "blocked", "pid", "pid_code", "pid_name", "pid_path" from (SELECT sg1.id AS gid,         su.lastName || ' ' || su.firstName || ' (' || su.subject || ')' AS gid_code,
                                 su.isblocked AS blocked,
               sg2.id AS pid,
               sg2.code AS pid_code,
               sg2.name AS pid_name,
               sh2.path_code AS pid_path
        FROM sys_h sh
        LEFT JOIN sys_h sh2 ON sh2.id = sh.parent_id
        LEFT JOIN sys_g sg1 ON sg1.id = sh.group_id
        LEFT JOIN sys_g sg2 ON sg2.id = sh2.group_id
        LEFT JOIN sys_u su ON sg1.code = su.subject
        WHERE su.isvisible = TRUE
          AND sh.parent_id IN
            (SELECT shh.id
             FROM sys_h shh
             LEFT JOIN sys_g sgg ON shh.group_id = sgg.id)
          AND sg1.type = 1
          AND sg2.type = 0
          AND sh.context = 0
          AND sh2.context = 0
        ORDER BY pid_code, pid, su.lastName, su.firstName) as native) as "query_alias"
where (( (  "pid" = '15874'  AND  "gid" = '5133'  ) OR ( (  "pid" = '15874'  AND  "gid" = '5130'  ) OR ( (  "pid" = '15874'  AND  "gid" = '5078'  ) OR ( (  "pid" = '15874'  AND  "gid" = '5116'  ) OR ( (  "pid" = '15874'  AND  "gid" = '26586'  ) OR ( (  "pid" = '15874'  AND  "gid" = '5106'  ) OR ( (  "pid" = '15874'  AND  "gid" = '5124'  ) OR ( (  "pid" = '15874'  AND  "gid" = '6675'  ) OR ( (  "pid" = '15874'  AND  "gid" = '5165'  ) OR ( (  "pid" = '5798'  AND  "gid" = '5865'  ) OR ( (  "pid" = '5867'  AND  "gid" = '5870'  ) OR ( (  "pid" = '5795'  AND  "gid" = '5865'  ) OR ( (  "pid" = '5795'  AND  "gid" = '5538'  ) OR ( (  "pid" = '5862'  AND  "gid" = '26613'  ) OR ( (  "pid" = '5862'  AND  "gid" = '26632'  ) OR ( (  "pid" = '5824'  AND  "gid" = '5833'  ) OR ( (  "pid" = '5854'  AND  "gid" = '5860'  ) OR ( (  "pid" = '5854'  AND  "gid" = '5857'  ) OR ( (  "pid" = '5854'  AND  "gid" = '26593'  ) OR ( (  "pid" = '5790'  AND  "gid" = '5793'  ) OR ( (  "pid" = '5819'  AND  "gid" = '5822'  ) OR ( (  "pid" = '5819'  AND  "gid" = '5225'  ) OR ( (  "pid" = '5843'  AND  "gid" = '5849'  ) OR ( (  "pid" = '5843'  AND  "gid" = '16360'  ) OR ( (  "pid" = '5843'  AND  "gid" = '5852'  ) OR ( (  "pid" = '5843'  AND  "gid" = '8313'  ) OR ( (  "pid" = '5814'  AND  "gid" = '5833'  ) OR ( (  "pid" = '5835'  AND  "gid" = '8337'  ) OR ( (  "pid" = '5835'  AND  "gid" = '5838'  ) OR ( (  "pid" = '5835'  AND  "gid" = '5817'  ) OR ( (  "pid" = '5835'  AND  "gid" = '26639'  ) OR ( (  "pid" = '5811'  AND  "gid" = '5833'  ) OR ( (  "pid" = '5827'  AND  "gid" = '26594'  ) OR ( (  "pid" = '5827'  AND  "gid" = '16328'  ) OR ( (  "pid" = '5787'  AND  "gid" = '5538'  ) OR ( (  "pid" = '5801'  AND  "gid" = '5804'  ) OR ( (  "pid" = '5801'  AND  "gid" = '5807'  ) OR ( (  "pid" = '5535'  AND  "gid" = '5538'  ) OR ( (  "pid" = '5591'  AND  "gid" = '5230'  ) OR ( (  "pid" = '5681'  AND  "gid" = '26634'  ) OR ( (  "pid" = '5681'  AND  "gid" = '5690'  ) OR ( (  "pid" = '5681'  AND  "gid" = '16051'  ) OR ( (  "pid" = '5681'  AND  "gid" = '26670'  ) OR ( (  "pid" = '5681'  AND  "gid" = '16035'  ) OR ( (  "pid" = '5681'  AND  "gid" = '5684'  ) OR ( (  "pid" = '5681'  AND  "gid" = '5687'  ) OR ( (  "pid" = '5681'  AND  "gid" = '16312'  ) OR ( (  "pid" = '5681'  AND  "gid" = '5287'  ) OR ( (  "pid" = '5227'  AND  "gid" = '5230'  ) OR ( (  "pid" = '5284'  AND  "gid" = '5290'  ) OR ( (  "pid" = '5284'  AND  "gid" = '26635'  ) OR ( (  "pid" = '6529'  AND  "gid" = '26575'  ) OR ( (  "pid" = '6532'  AND  "gid" = '6528'  ) OR ( (  "pid" = '6532'  AND  "gid" = '26599'  ) OR ( (  "pid" = '6532'  AND  "gid" = '26617'  ) OR ( (  "pid" = '6532'  AND  "gid" = '26605'  ) OR ( (  "pid" = '6532'  AND  "gid" = '5520'  ) OR ( (  "pid" = '5484'  AND  "gid" = '5525'  ) OR ( (  "pid" = '5522'  AND  "gid" = '8331'  ) OR ( (  "pid" = '5459'  AND  "gid" = '5520'  ) OR ( (  "pid" = '5505'  AND  "gid" = '5528'  ) OR ( (  "pid" = '5505'  AND  "gid" = '5727'  ) OR ( (  "pid" = '5505'  AND  "gid" = '26604'  ) OR ( (  "pid" = '5505'  AND  "gid" = '5482'  ) OR ( (  "pid" = '5505'  AND  "gid" = '5508'  ) OR ( (  "pid" = '5505'  AND  "gid" = '8934'  ) OR ( (  "pid" = '5505'  AND  "gid" = '5584'  ) OR ( (  "pid" = '5505'  AND  "gid" = '26589'  ) OR ( (  "pid" = '5474'  AND  "gid" = '5477'  ) OR ( (  "pid" = '5500'  AND  "gid" = '5265'  ) OR ( (  "pid" = '5500'  AND  "gid" = '5503'  ) OR ( (  "pid" = '5495'  AND  "gid" = '5498'  ) OR ( (  "pid" = '5466'  AND  "gid" = '5469'  ) OR ( (  "pid" = '5487'  AND  "gid" = '5490'  ) OR ( (  "pid" = '5096'  AND  "gid" = '5078'  ) OR ( (  "pid" = '5113'  AND  "gid" = '5116'  ) OR ( (  "pid" = '5154'  AND  "gid" = '5116'  ) OR ( (  "pid" = '5162'  AND  "gid" = '5165'  ) OR ( (  "pid" = '5108'  AND  "gid" = '5111'  ) OR ( (  "pid" = '5135'  AND  "gid" = '5141'  ) OR ( (  "pid" = '5135'  AND  "gid" = '5138'  ) OR ( (  "pid" = '5135'  AND  "gid" = '8937'  ) OR ( (  "pid" = '5135'  AND  "gid" = '5147'  ) OR ( (  "pid" = '5151'  AND  "gid" = '5116'  ) OR ( (  "pid" = '5157'  AND  "gid" = '5160'  ) OR ( (  "pid" = '5075'  AND  "gid" = '5078'  ) OR ( (  "pid" = '5075'  AND  "gid" = '5081'  ) OR ( (  "pid" = '5710'  AND  "gid" = '5713'  ) OR ( (  "pid" = '5750'  AND  "gid" = '5771'  ) OR ( (  "pid" = '5750'  AND  "gid" = '5774'  ) OR ( (  "pid" = '5750'  AND  "gid" = '5777'  ) OR ( (  "pid" = '5750'  AND  "gid" = '5759'  ) OR ( (  "pid" = '5750'  AND  "gid" = '26671'  ) OR ( (  "pid" = '5750'  AND  "gid" = '26607'  ) OR ( (  "pid" = '5750'  AND  "gid" = '5765'  ) OR ( (  "pid" = '5750'  AND  "gid" = '26672'  ) OR ( (  "pid" = '5750'  AND  "gid" = '26620'  ) OR ( (  "pid" = '5750'  AND  "gid" = '5762'  ) OR ( (  "pid" = '5750'  AND  "gid" = '26602'  ) OR ( (  "pid" = '5750'  AND  "gid" = '8309'  ) OR ( (  "pid" = '5750'  AND  "gid" = '5783'  ) OR ( (  "pid" = '5750'  AND  "gid" = '5780'  ) OR ( (  "pid" = '5750'  AND  "gid" = '5768'  ) OR ( (  "pid" = '5556'  AND  "gid" = '5549'  ) OR ( (  "pid" = '5705'  AND  "gid" = '5708'  ) OR ( (  "pid" = '5715'  AND  "gid" = '5665'  ) OR ( (  "pid" = '5715'  AND  "gid" = '5742'  ) OR ( (  "pid" = '5715'  AND  "gid" = '8319'  ) OR ( (  "pid" = '5715'  AND  "gid" = '5745'  ) OR ( (  "pid" = '5715'  AND  "gid" = '5718'  ) OR ( (  "pid" = '5715'  AND  "gid" = '5748'  ) OR ( (  "pid" = '5715'  AND  "gid" = '5721'  ) OR ( (  "pid" = '5715'  AND  "gid" = '5724'  ) OR ( (  "pid" = '5715'  AND  "gid" = '5733'  ) OR ( (  "pid" = '5715'  AND  "gid" = '5736'  ) OR ( (  "pid" = '5551'  AND  "gid" = '5554'  ) OR ( (  "pid" = '5551'  AND  "gid" = '5768'  ) OR ( (  "pid" = '5692'  AND  "gid" = '5695'  ) OR ( (  "pid" = '5692'  AND  "gid" = '26588'  ) OR ( (  "pid" = '5692'  AND  "gid" = '5698'  ) OR ( (  "pid" = '5692'  AND  "gid" = '5701'  ) OR ( (  "pid" = '5586'  AND  "gid" = '5589'  ) OR ( (  "pid" = '5667'  AND  "gid" = '26595'  ) OR ( (  "pid" = '5667'  AND  "gid" = '5670'  ) OR ( (  "pid" = '5667'  AND  "gid" = '5676'  ) OR ( (  "pid" = '5667'  AND  "gid" = '5679'  ) OR ( (  "pid" = '5667'  AND  "gid" = '26664'  ) OR ( (  "pid" = '5546'  AND  "gid" = '5549'  ) OR ( (  "pid" = '5581'  AND  "gid" = '5462'  ) OR ( (  "pid" = '5576'  AND  "gid" = '5579'  ) OR ( (  "pid" = '5636'  AND  "gid" = '5645'  ) OR ( (  "pid" = '5636'  AND  "gid" = '16344'  ) OR ( (  "pid" = '5636'  AND  "gid" = '5639'  ) OR ( (  "pid" = '5636'  AND  "gid" = '5642'  ) OR ( (  "pid" = '5636'  AND  "gid" = '26652'  ) OR ( (  "pid" = '5636'  AND  "gid" = '5662'  ) OR ( (  "pid" = '5636'  AND  "gid" = '5651'  ) OR ( (  "pid" = '5568'  AND  "gid" = '5571'  ) OR ( (  "pid" = '5623'  AND  "gid" = '5626'  ) OR ( (  "pid" = '5563'  AND  "gid" = '5566'  ) OR ( (  "pid" = '5594'  AND  "gid" = '26603'  ) OR ( (  "pid" = '5594'  AND  "gid" = '5606'  ) OR ( (  "pid" = '5594'  AND  "gid" = '5615'  ) OR ( (  "pid" = '5594'  AND  "gid" = '5597'  ) OR ( (  "pid" = '5594'  AND  "gid" = '26659'  ) OR ( (  "pid" = '5594'  AND  "gid" = '5603'  ) OR ( (  "pid" = '5594'  AND  "gid" = '5618'  ) OR ( (  "pid" = '5594'  AND  "gid" = '5621'  ) OR ( (  "pid" = '5594'  AND  "gid" = '5612'  ) OR ( (  "pid" = '5594'  AND  "gid" = '5609'  ) OR ( (  "pid" = '5543'  AND  "gid" = '5533'  ) OR ( (  "pid" = '5530'  AND  "gid" = '5554'  ) OR ( (  "pid" = '5530'  AND  "gid" = '5533'  ) OR ( (  "pid" = '5573'  AND  "gid" = '5631'  ) OR ( (  "pid" = '5628'  AND  "gid" = '8311'  ) OR ( (  "pid" = '5628'  AND  "gid" = '5634'  ) OR ( (  "pid" = '5628'  AND  "gid" = '26601'  ) OR ( (  "pid" = '5085'  AND  "gid" = '5078'  ) OR ( (  "pid" = '5085'  AND  "gid" = '5081'  ) OR ( (  "pid" = '5085'  AND  "gid" = '5768'  ) OR ( (  "pid" = '5103'  AND  "gid" = '5106'  ) OR ( (  "pid" = '5118'  AND  "gid" = '5133'  ) OR ( (  "pid" = '5118'  AND  "gid" = '5130'  ) OR ( (  "pid" = '5118'  AND  "gid" = '5124'  ) OR ( (  "pid" = '5540'  AND  "gid" = '5533'  ) OR ( (  "pid" = '5319'  AND  "gid" = '5322'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5433'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5348'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5403'  ) OR ( (  "pid" = '5397'  AND  "gid" = '8329'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5427'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5448'  ) OR ( (  "pid" = '5397'  AND  "gid" = '8321'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5439'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5424'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5412'  ) OR ( (  "pid" = '5397'  AND  "gid" = '26669'  ) OR ( (  "pid" = '5397'  AND  "gid" = '26606'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5436'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5454'  ) OR ( (  "pid" = '5397'  AND  "gid" = '26592'  ) OR ( (  "pid" = '5397'  AND  "gid" = '26651'  ) OR ( (  "pid" = '5397'  AND  "gid" = '26590'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5451'  ) OR ( (  "pid" = '5397'  AND  "gid" = '5400'  ) OR ( (  "pid" = '5316'  AND  "gid" = '5190'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5377'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5389'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5359'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5365'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5374'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5356'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5386'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5380'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5392'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5314'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5383'  ) OR ( (  "pid" = '5353'  AND  "gid" = '5371'  ) OR ( (  "pid" = '5187'  AND  "gid" = '5190'  ) OR ( (  "pid" = '5311'  AND  "gid" = '5314'  ) OR ( (  "pid" = '5324'  AND  "gid" = '26598'  ) OR ( (  "pid" = '5324'  AND  "gid" = '8333'  ) OR ( (  "pid" = '5324'  AND  "gid" = '5327'  ) OR ( (  "pid" = '5324'  AND  "gid" = '5342'  ) OR ( (  "pid" = '5324'  AND  "gid" = '5339'  ) OR ( (  "pid" = '5324'  AND  "gid" = '5333'  ) OR ( (  "pid" = '5324'  AND  "gid" = '8317'  ) OR ( (  "pid" = '5324'  AND  "gid" = '5351'  ) OR ( (  "pid" = '5324'  AND  "gid" = '5345'  ) OR ( (  "pid" = '5324'  AND  "gid" = '26615'  ) OR ( (  "pid" = '5324'  AND  "gid" = '5330'  ) OR ( (  "pid" = '5324'  AND  "gid" = '5127'  ) OR ( (  "pid" = '5324'  AND  "gid" = '5336'  ) OR ( (  "pid" = '5182'  AND  "gid" = '5185'  ) OR ( (  "pid" = '5292'  AND  "gid" = '5301'  ) OR ( (  "pid" = '5292'  AND  "gid" = '26586'  ) OR ( (  "pid" = '5292'  AND  "gid" = '5304'  ) OR ( (  "pid" = '5292'  AND  "gid" = '5298'  ) OR ( (  "pid" = '5292'  AND  "gid" = '5295'  ) OR ( (  "pid" = '5292'  AND  "gid" = '26662'  ) OR ( (  "pid" = '5292'  AND  "gid" = '26658'  ) OR ( (  "pid" = '5222'  AND  "gid" = '5273'  ) OR ( (  "pid" = '5270'  AND  "gid" = '26591'  ) OR ( (  "pid" = '5270'  AND  "gid" = '26614'  ) OR ( (  "pid" = '5270'  AND  "gid" = '5282'  ) OR ( (  "pid" = '5204'  AND  "gid" = '5207'  ) OR ( (  "pid" = '5232'  AND  "gid" = '8987'  ) OR ( (  "pid" = '5232'  AND  "gid" = '26667'  ) OR ( (  "pid" = '5232'  AND  "gid" = '5241'  ) OR ( (  "pid" = '5232'  AND  "gid" = '5244'  ) OR ( (  "pid" = '5177'  AND  "gid" = '5180'  ) OR ( (  "pid" = '5217'  AND  "gid" = '5220'  ) OR ( (  "pid" = '5262'  AND  "gid" = '5265'  ) OR ( (  "pid" = '5262'  AND  "gid" = '5268'  ) OR ( (  "pid" = '5262'  AND  "gid" = '8984'  ) OR ( (  "pid" = '5214'  AND  "gid" = '5180'  ) OR ( (  "pid" = '5257'  AND  "gid" = '5260'  ) OR ( (  "pid" = '5209'  AND  "gid" = '5212'  ) OR ( (  "pid" = '5246'  AND  "gid" = '5255'  ) OR ( (  "pid" = '5246'  AND  "gid" = '5252'  ) OR ( (  "pid" = '5246'  AND  "gid" = '5249'  ) OR ( (  "pid" = '5174'  AND  "gid" = '5094'  ) OR ( (  "pid" = '5197'  AND  "gid" = '26665'  ) OR ( (  "pid" = '5197'  AND  "gid" = '26575'  ) OR ( (  "pid" = '5091'  AND  "gid" = '5078'  ) OR ( (  "pid" = '5091'  AND  "gid" = '26575'  ) OR ( (  "pid" = '5091'  AND  "gid" = '5094'  ) OR ( (  "pid" = '5169'  AND  "gid" = '5172'  ) OR ( (  "pid" = '5192'  AND  "gid" = '8325'  ) OR ( (  "pid" = '5192'  AND  "gid" = '6683'  ) OR ( (  "pid" = '5192'  AND  "gid" = '5195'  ) OR ( (  "pid" = '5083'  AND  "gid" = '5078'  ) OR ( (  "pid" = '5083'  AND  "gid" = '5081'  ) OR ( (  "pid" = '5083'  AND  "gid" = '5768'  ) OR ( (  "pid" = '5087'  AND  "gid" = '5078'  ) OR (  "pid" = '5087'  AND  "gid" = '5081'  ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ))


/opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/indexer.rb:180:in `each': stack level too deep (SystemStackError)
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/indexer.rb:180:in `find_by_key'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/indexer.rb:184:in `block in find_by_key'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/indexer.rb:180:in `each'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/indexer.rb:180:in `find_by_key'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/indexer.rb:188:in `block in find_by_key'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/indexer.rb:188:in `each'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/indexer.rb:188:in `flat_map'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/indexer.rb:188:in `find_by_key'
         ... 1354 levels...
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/processor.rb:49:in `process_queries'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/processor.rb:28:in `block (2 levels) in perform'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/processor.rb:26:in `loop'
        from /opt/dexter/vendor/bundle/ruby/2.3.0/bundler/gems/dexter-c45e477af76f/lib/dexter/processor.rb:26:in `block in perform'
```

anyway query is stupid and we must fix it ;)

**Comment by ankane** [comment]
Hey @embrance, I'm not sure what the issue is. I put together [this gist](https://gist.github.com/ankane/889930806a596af2c175284a42c63c37) of the logic and can't reproduce.

**Comment by ankane** [comment]
Hey @embrance, this issue is getting stale, so going to close. Please let me know if you have any updates.
