### ISSUE TITLE
JSON::NestingError error again

### ISSUE THREAD

**Issue by pdonovan** [ankane/dexter#46]
Hi,

Seems similar to issue #25 , perhaps it's a regression?

```
/usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/json/common.rb:216:in `parse': nesting of 101 is too deep (JSON::NestingError)
	from /usr/local/Cellar/ruby/3.2.2/lib/ruby/3.2.0/json/common.rb:216:in `parse'
	from /usr/local/Cellar/dexter/0.5.0/libexec/gems/pgdexter-0.5.0/lib/dexter/indexer.rb:229:in `find_columns'
	from /usr/local/Cellar/dexter/0.5.0/libexec/gems/pgdexter-0.5.0/lib/dexter/indexer.rb:200:in `block in create_hypothetical_indexes'
	from /usr/local/Cellar/dexter/0.5.0/libexec/gems/pgdexter-0.5.0/lib/dexter/indexer.rb:198:in `each'
	from /usr/local/Cellar/dexter/0.5.0/libexec/gems/pgdexter-0.5.0/lib/dexter/indexer.rb:198:in `create_hypothetical_indexes'
	from /usr/local/Cellar/dexter/0.5.0/libexec/gems/pgdexter-0.5.0/lib/dexter/indexer.rb:99:in `process_queries'
	from /usr/local/Cellar/dexter/0.5.0/libexec/gems/pgdexter-0.5.0/lib/dexter/indexer.rb:32:in `process_stat_statements'
	from /usr/local/Cellar/dexter/0.5.0/libexec/gems/pgdexter-0.5.0/lib/dexter/client.rb:27:in `perform'
	from /usr/local/Cellar/dexter/0.5.0/libexec/gems/pgdexter-0.5.0/lib/dexter/client.rb:9:in `start'
	from /usr/local/Cellar/dexter/0.5.0/libexec/gems/pgdexter-0.5.0/exe/dexter:7:in `<top (required)>'
	from /usr/local/Cellar/dexter/0.5.0/libexec/bin/dexter:25:in `load'
	from /usr/local/Cellar/dexter/0.5.0/libexec/bin/dexter:25:in `<main>'
```

**Comment by ankane** [comment]
Hi @pdonovan, thanks for reporting! Same error, but in a different part of the code. Fixed in the commit above.
