### ISSUE TITLE
Error "invalid input syntax for type bigint" on --min-calls parameter

### ISSUE THREAD

**Issue by dmorel** [ankane/dexter#53]
```text
❯ exe/dexter -d ********* --pg-stat-statements -h localhost -U ********** -p 2002 --min-calls 10
/opt/homebrew/lib/ruby/gems/3.3.0/gems/pgdexter-0.5.4/lib/dexter/indexer.rb:548:in `exec_params': ERROR:  invalid input syntax for type bigint: "10.0" (PG::InvalidTextRepresentation)
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/pgdexter-0.5.4/lib/dexter/indexer.rb:548:in `block in execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/pgdexter-0.5.4/lib/dexter/indexer.rb:544:in `synchronize'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/pgdexter-0.5.4/lib/dexter/indexer.rb:544:in `execute'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/pgdexter-0.5.4/lib/dexter/indexer.rb:685:in `stat_statements'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/pgdexter-0.5.4/lib/dexter/indexer.rb:30:in `process_stat_statements'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/pgdexter-0.5.4/lib/dexter/client.rb:27:in `perform'
	from /opt/homebrew/lib/ruby/gems/3.3.0/gems/pgdexter-0.5.4/lib/dexter/client.rb:9:in `start'
	from exe/dexter:7:in `<main>'
```

This is with dexter on main (0.5.4) on Sonoma/M1 and PG 13.13 on RDS

**Comment by ankane** [comment]
Hi @dmorel, thanks for reporting! Fixed in the commit above.
